language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls pytest-cov pytest Biopython docx
  - pip install bokeh pandas
  - pip install -e .
# command to run tests
script:
  - python -m pytest -v --cov crazydoc --cov-report term-missing

after_success:
  - coveralls